### ISSUE TITLE
Add support for custom changelog format

### ISSUE THREAD

**Issue by Klemensas** [ButlerLogic/action-autotag#14]
I'd like to use the default changelog as the message but the formatting of the changelog is something I'd like to customize.
So it'd be nice if this would accept another input with a custom format.

I imagine it could be some string with special tags that denote variables. For example:
```yml
  changelog_structure:
    description: "A string denoting changelog format. Supports `{{message}}`, `{{author}}` and `{{sha}}`. Defaults to `**1) {{message}}** {{author}}\n(SHA: {{sha}})\n` Only used when tag_message is empty."
    required: false
```

If you decide to go forward with this it would be really nice to be able to also include only the message headline instead of the full commit message since they can get verbose and changelogs work best as short summaries.
