### ISSUE TITLE
HttpError: Could not verify tag name

### ISSUE THREAD

**Issue by svetlyak40wt** [ButlerLogic/action-autotag#36]
**Issue:**

I receive this error when trying to use action:

```
Skipping min version check. 1.17.0 (2022-11-11) is not valid SemVer
Notice: Recognized "1.17.0 (2022-[11](https://github.com/ultralisp/ultralisp/actions/runs/3448090317/jobs/5754777700#step:4:12)-11)" using the regex extraction with the /^(?<version>\d+\.\d+\.\d+(.+)?)\n?/gim pattern..
Attempting to create v1.17.0 (2022-11-11) tag.
Warning: Could not verify tag name
Warning: HttpError: Could not verify tag name
    at /home/runner/work/_actions/butlerlogic/action-autotag/8bc1ad456dcdee34e8c6ffbce991cc31793578c2/dist/main.js:7954:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Tag.push (/home/runner/work/_actions/butlerlogic/action-autotag/8bc1ad456dcdee34e8c6ffbce991cc31793578c2/dist/main.js:27[14](https://github.com/ultralisp/ultralisp/actions/runs/3448090317/jobs/5754777700#step:4:15)0:22)
    at async run (/home/runner/work/_actions/butlerlogic/action-autotag/8bc1ad456dcdee34e8c6ffbce991cc3[17](https://github.com/ultralisp/ultralisp/actions/runs/3448090317/jobs/5754777700#step:4:18)93578c2/dist/main.js:27290:7)
```

Here is the [test run](https://github.com/ultralisp/ultralisp/actions/runs/3448090317/jobs/5754777700). There is a `lannonbr/repo-permission-check-action` step to check if current user has `write` permission.

This is the full content of the workflow:

```
name: Add Version Tag

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ${{ github.actor }} permission check to update release version
      uses: "lannonbr/repo-permission-check-action@2.0.2"
      with:
        permission: "write"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: butlerlogic/action-autotag@8bc1ad456dcdee34e8c6ffbce991cc31793578c2
      with:
        regex_pattern: "^(?<version>\\d+\\.\\d+\\.\\d+(.+)?)\\n?"
        root: ./ChangeLog.rst
        tag_prefix: "v"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
