### ISSUE TITLE
failing with `Bad credentials` when pushing a tag to remote

### ISSUE THREAD

**Issue by Svetlanko** [ButlerLogic/action-autotag#40]
**Issue:**
The `stable` build fails to push a tag to the remote:
```bash
Warning: Attempting to use regex version extraction strategy.
Warning: Attempting to create v3.0.3 tag.
Warning: Bad credentials
Warning: HttpError: Bad credentials
    at /app/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Tag.getTags (file:///app/lib/tag.js:92:18)
    at async Tag.exists (file:///app/lib/tag.js:102:[18](https://github.com/Svetlanko/fiery-lion-template/actions/runs/4057414256/jobs/6983140082#step:4:19))
    at async run (file:///app/main.js:59:9)
```

**How To Reproduce:**
the setup with a `regex` pattern(reading version number from a `version` file):
```yml
name: Tag Release

on:
  push:
    paths:
      - version
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name:  Create a tag
        uses: butlerlogic/action-autotag@stable
        with:
          strategy: regex
          root: "version"
          regex_pattern: "(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "{{ secrets.GITHUB_TOKEN }}"
          ACTIONS_STEP_DEBUG: true  #purely for debugging purpose
```

**Expected Behavior:**
a new tag is pushed and available in the remote

A screen with logs:
<img width="588" alt="Screen Shot 2023-01-31 at 11 57 53 AM" src="https://user-images.githubusercontent.com/2976439/215869037-a06f6ab9-f74a-4479-8d39-1313763161a8.png">
<img width="625" alt="Screen Shot 2023-01-31 at 11 05 18 AM" src="https://user-images.githubusercontent.com/2976439/215867285-86c94c93-5afc-4806-a7a8-38848f048316.png">

I tested several combinations:
1. non-regex pattern
2. using this setup in the private repository in a personal account
3. using this setup in the private repository as part of GitHub Enterprise 
4. using a PAT(personal token) instead of `secrets.GITHUB_TOKEN`
in all of these cases, the error is the same. 

Using `master` build vs `stable` gave different errors.
`secrets.GITHUB_TOKEN` works with other GitHub actions, which makes me think the token is not issue.

❓ Would you be able to recommend anything else to try? or suggest a fix? thank you 🙏
