### ISSUE TITLE
Token from secrets.GITHUB_TOKEN does not work without a permission to write "contents"

### ISSUE THREAD

**Issue by svetlyak40wt** [ButlerLogic/action-autotag#47]
When using job description from the README:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: butlerlogic/action-autotag@stable
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

I've got "Resource not accessible" error in action logs:

![Screenshot 2023-12-07 at 18 37 03](https://github.com/ButlerLogic/action-autotag/assets/24827/28e1779a-ea50-4f44-9b88-5ee43ae5468e)

To solve this problem, `permissions` section should be added tot he job's declaration:

```
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: butlerlogic/action-autotag@stable
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
