### ISSUE TITLE
Using Manual Version Tag Is Being Ignored

### ISSUE THREAD

**Issue by ThePieMonster** [ButlerLogic/action-autotag#48]
I have the following code in my github actions. The run command from the first task here shows version 1.0.1, however the AutoTag task is using the version found in package.json which is 1.0.0. 

How can I get Auto Tag to use a specific tag version?

```
      - name: Tag Version To Use
        run: echo "${{ steps.version_increment.outputs.version }}"

      - name: Auto Tag
        uses: butlerlogic/action-autotag@1.1.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: "${{ steps.version_increment.outputs.version }}"`
```

The setup is being followed from here:

<img width="648" alt="image" src="https://github.com/ButlerLogic/action-autotag/assets/11359134/43257c83-a0cc-4034-9ffc-5582325ca7f8">
