### ISSUE TITLE
Get tag from previous step output instead

### ISSUE THREAD

**Issue by jacobtomlinson** [ButlerLogic/action-autotag#8]
Thanks for working on this awesome action.

I'd love to use this in a non-JavaScript project and therefore there is no `package.json` file. However I can easily get the version in a previous step and store it as an output. 

For example I have written an [Action which exposes a Helm Chart's metadata](https://github.com/jacobtomlinson/gha-read-helm-chart) by reading the `Chart.yaml` file and exposing the values as outputs. I'd like to autotag if the version specified in my chart changes.

Therefore could an input be added here to allow you to specify the version and bypass the `package.json` logic?

Something like this

```yaml
name: My Workflow

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: some/action@master  # This action exposes the app `version` as an output
      id: getversion
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        version: ${{ steps.getversion.outputs.version }}
```
